<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Password Generator - Create Strong, Random, and Hard to crack Password</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Strong Random Password Generator. This password generator creates a secure password that is hard to guess and impossible to crack."> 
    <meta name="keywords" content="Password Generator, Online Password Generator, Random Password Generator, Secure Password Generator, Create strong Password, Generate strong Password" >
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href=css/style.css">
<style>

</style>
</head>
<body>
<div id="main">
    <a href="https://techlomedia.in/tools/">Home</a> | <a href="https://gaming.techlomedia.in/">Gaming Zone</a>
<h1>Random Password Generator</h1>
<p>This is a random password generator that generates a strong password. The password generated by this random password generator will not be easy to crack using a dictionary or Brute Force attack.</p>
<p><i>We have already excluded similar characters such as i,l,1,L from the password to avoid any confusion.</i></p>
<div>
<div style="text-align: center; background: aliceblue; padding: 20px">
<h3>Your random password is:</h3>
<div id="pass"></div>
<br />
<!-- <button class="copy btn" data-clipboard-target="#pass">Copy password</button> -->
<div class="wrapper">
    <button data-clipboard-target="#pass" class="copy">
        <span class="lp-pg-tooltip-content" style="display: none;">Copy</span>
    </button>
    <button class="generate" style="">
        <span class="lp-pg-tooltip-content" style="display: none;">Generate</span>
    </button>
</div>
<hr />
<div id="entropy"></div>
<hr/>
<form method="POST">
    <table>
        <tr>
            <td>Password Length</td>
            <td>
                <input type="range" class="form-range" value="10" min="8" max="50" step="1" id="length" oninput="plength.value = length.value" onchange="genPassword()">
                <output name="plength" id="plength">10</output>
            </td>
        </tr>
        <tr>
            <td>Include lower case ( e.g. abcdefgh )</td>
            <td>
                <label class="switch">
                    <input type="checkbox" name="alphal" id="alphal" checked onchange="genPassword()" />
                    <span class="slider round"></span>
                </label>
            </td>
        </tr>
        <tr>
            <td>Include Upper case ( e.g. ABCDEFGH )</td>
            <td>
                <label class="switch">
                    <input type="checkbox" name="alphac" id="alphac" checked onchange="genPassword()" />
                    <span class="slider round"></span>
                </label>
            </td>
        </tr>
        <tr>
            <td>Include Numbers ( e.g. 123456 )</td>
            <td>
                <label class="switch">
                    <input type="checkbox" name="number" id="number" checked onchange="genPassword()" />
                    <span class="slider round"></span>
                </label>
            </td>
        </tr>
        <tr>
            <td>Include Special Characters ( e.g. @#$% )</td>
            <td>
                <label class="switch">
                    <input type="checkbox" name="special" id="special" checked onchange="genPassword()"  />
                    <span class="slider round"></span>
                </label>
            </td>
        </tr>
        <tr>
            <td colspan="2"></td>
        </tr>
    </table>
</form>
</div>
<div>
<br />    
    <a href="https://techlomedia.in/refer/nordpass" target="_blank"><img src="img/nordpass.jpeg" style="width:95%; height:auto;" /></a>
<br />
<br />
<h3>Strong Password Generator</h3>
<p>This is a simple password generator that considers several factors while generating a random password. All the passwords generated by this tool will be hard to crack using social engineering, dictionary attack or brute force attacks. You can already see that these passwords are also really hard to guess.</p>
</div>    
</div>
<br /><hr /><br />

<p>It is really important to have a strong password. Passwords can be guessed or cracking using brute force attack. To prevent these things, you need to have a strong password. Although strong passwords are not easy to remember, they are also safe. If you find it hard to remember the strong password, you should start using a good password manager. Password is the key to your bank account and different web accounts. So, you need to select a strong password and keep it safe.</p>

<strong>What is a strong password?</strong>
<p>A password is strong when it contains a mix of characters, numbers, and special characters. It should also contains characters in both small and capital cases. Password length should also be more than 8. These things make a password strong.</p>

<strong>What is Password Entropy?</strong>
<p></p>Password Entropy denotes the password strength. It basically tells how strong the password is against a brute-force attacks. Bigger the Entropy, the harder a password is to crack.</p>

<strong>How to remember a strong but random password?</strong>
<p>I know it is really hard to remember a random password with mix or characters, numbers, and special characters. So, I recommend people <a href="https://techlomedia.in/refer/nordpass" target="_blank">NordPass</a>. It is a good and free password manager to keep your password safe.</p>

<strong>What are some tips to keep my web accounts safe?</strong>
<p>You should follow these tips to keep your web accounts and password safe:</p>
<ol>
<li>Always select a different password for different account. Never reuse the same password in multiple accounts. What if hackers manage to hack one of these websites and get your email and password combination. They will try this conbination on several other websites. If you use the same email and password combination at more than once places, your web accounts will be at risk.</li>
<li>Do not use phone numbers and names of your family members as password.</li>
<li>Avoid using keyboard key sequences as password. For example: qwertyui, asdfghj, zxcvbnm, etc. These are really easy to crack using dictionary or Bruteforce attack even if they look like a random password.</li>
<li>Stop keeping your passwords in Notes app or in any text file. You should use a <a href="https://techlomedia.in/top-apps/best-password-managers/">good password manager</a> for keeping your passwords safe.</li> 
<li>It is also recommended to change your passwords in a regular interval.</li>
<li>Do not share your passwords with anyone</li>
</ol>

<br />
<div class="footer">
    <ul>
        <li><a href="https://techlomedia.in/about-us/">About Us</a></li><li><a href="https://techlomedia.in/our-editorial-team/">Our Team</a></li><li><a href="https://techlomedia.in/advertise/">Advertise</a></li><li><a href="https://techlomedia.in/terms-and-conditions/">Terms &#038; conditions</a></li><li><a href="https://techlomedia.in/privacy-policy-techlomedia/">Privacy Policy</a></li><li><a href="https://techlomedia.in/contact-us/">Contact</a></li>
    </ul>
    <p style="text-align:center"><small>&copy; Techomedia Internet Pvt Ltd.</small></p>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.1/clipboard.min.js"></script>
<script type="text/javascript">
    function genPassword() {
            var chars = "0123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*()ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            var chars1="";
            if($('#alphal').is(":checked"))
            {
                chars1+='abcdefghijkmnopqrstuvwxyz';
            }
            if($('#alphac').is(":checked"))
            {
                chars1+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
            }
            if($('#number').is(":checked"))
            {
                chars1+='023456789';
            }
            if($('#special').is(":checked"))
            {
                chars1+='!#$%&()*+,-./:;<=>?@[\]^_{|}~';
            }

            var passwordLength = $("#length").val();
            if(chars1!='')
            {
                chars=chars1;
            }
            var password = "";
            for (var i = 0; i <= passwordLength; i++) {
              var randomNumber = Math.floor(Math.random() * chars.length);
              password += chars.charAt(randomNumber);
            }
            $('div#pass').text(password);
            
            var entropy = Math.log2(chars.length)*passwordLength;
            var time = Math.pow(2,entropy);
            $('div#entropy').text("Password Entropy: "+entropy.toFixed(2)+" bits ");
        }
    window.onload = function () {
        genPassword();
        $('.copy').tooltip({
          trigger: 'click',
          placement: 'bottom'
        });
        
        function setTooltip(btn, message) {
          btn.tooltip('hide')
            .attr('data-original-title', message)
            .tooltip('show');
        }
        
        function hideTooltip(btn) {
          setTimeout(function() {
            btn.tooltip('hide');
          }, 1000);
        }
     var clipboard = new Clipboard('.copy')

        clipboard.on('success', function (e) {
          var btn = $(e.trigger);
          setTooltip(btn, 'Copied');
          hideTooltip(btn);
          e.clearSelection()
        })
        clipboard.on('error', function (e) {
          console.error('Action:', e.action)
          console.error('Trigger:', e.trigger)
        })
        
        $(".generate").click(function(){
            genPassword();
        });

    }
  </script>
</body>
</html>